### ISSUE TITLE
关于代码的功能寻找

### ISSUE THREAD

**Issue by sunyulin950824** [MediaBrain-SJTU/FedSkip#1]
尊敬的作者，您好，
很荣幸拜读到您的论文，我对跳跃聚合很感兴趣想要加入到自己的代码中。
我有一个问题，想要问问您。
在跳跃聚合中，不执行联邦平均时，服务器将接收到的模型打乱发送给不同的客户端，
上述这句功能对应的是哪段代码，我实在是没找到。
感谢您的帮助，谢谢您

**Comment by knight-fzq** [comment]
你好！
非常感谢我的工作能够对你有帮助，对于你的问题，我觉得在main_skip.py文件中Line 301-302 和Line 314可以找到答案。Line 302我对用户ID做了打乱，在Line 314时对是否跳跃的条件做判断，然后判断是否执行聚合命令。如果你还有后续问题，可以发邮件到ziqingfan0331@gmail.com或者zqfan_knight@sjtu.edu.cn这样可以更快捷的联系到我。
